### PR TITLE
#59: !join can allow players to join case-sensitive teams

### LINKED ISSUE #59: !join can allow players to join case-sensitive teams
When creating a new game where the reader adds the teams, any mistakes in capitalization of the team name will cause the player to join a team who's name appears under a different team when !score is called.

**Steps to Reproduce**
1. With Team Prefix disabled, create a new game
2. Create 2 team names, such as "Alpha" and "Beta"
3. have someone attempt to join team "alpha"
4. run !score. There should be 3 teams listed, with an "Alpha" and "Alpha", though one was created lowercase

**Expected Behavior**
A 3rd team is not created, either the command fails ("no team named alpha") or they are automatically added to the existing team

This seems to happen somewhat inconsistently, and the third team may only appear when someone is actually on the team

### PR DESCRIPTION
**Pull request by Sam-per**
- Forces all case variations of team names to return to the original spelling

When calling !score when teammates would fail to use the same casing in their team name, it would result in situations where the call would succeed (as the dictionary was case-insensitive), but the player's team name would use the player's casing. This would result in the scoreboard having players on team Alpha and team ALPHA listed separately.

One peculiarity of the current solution is that the success message still uses the user's casing of their team name, even though they will be added to the correct casing team. In the example from the test cases, the player succeeds in joining team Alpha using command !join ALPHA with a response message "@mention is on ALPHA"

Resolves #59

### CODE REVIEW

**Comment by alopezlago** [comment]
There's a couple way to fix the peculiarity:
1. Make TryAddPlayerToTeam return the proper team name in an out parameter
2. In GeneralCommandHandler.JoinTeamAsync, call teamManager.GetTeamIdOrNull with the player's ID, then use teamManager.GetTeamIdToName to get the proper team name. 
    - You don't technically need to do the second part with how it's implemented now, but we'd be  relying on the behavior of a specific implementation of ISelfManagedTeamManager where teamId is the same as teamName, which isn't something we guarantee.

Let me know if you want to address the peculiarity.

**Comment by Sam-per** [comment]
I ended up going with the second option you listed (GetTeamIdOrNull into GetTeamIdToBame).

Needless to say, it was a lot easier to update than changing the method signature of TryAddPlayerToTeam

File: QuizBowlDiscordScoreTracker/Commands/GeneralCommandHandler.cs [hunk 1]
```diff
@@ -83,6 +83,8 @@ public Task JoinTeamAsync(string teamName)
                     $@"Couldn't join team ""{teamName}"". Make sure it is not misspelled.");
             }
 
+            string teamId = game.TeamManager.GetTeamIdOrNull(this.Context.User.Id).Result;
```
Comment (alopezlago) [inline QuizBowlDiscordScoreTracker/Commands/GeneralCommandHandler.cs:86]: Convert this method to async, then await on these two methods. Better to use async/await than make this synchronous.

**Review by alopezlago — CHANGES_REQUESTED** [review]
Just use await/async in JoinTeamAsync instead of using .Result, which makes them synchronous.

**Review by alopezlago — APPROVED** [review]
